name: Upload Release Assets

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  STATIC_ASSET_NAME: ${{ vars.STATIC_ASSET_NAME }}
  BUILD_OUTPUT_FOLDER: ${{ vars.BUILD_OUTPUT_FOLDER }}

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build static site
        run: pnpm generate:web

      - name: Zip generated static site
        run: |
          [ ! -d "$BUILD_OUTPUT_FOLDER" ] && echo "Build output not found!" && exit 1
          mv "$BUILD_OUTPUT_FOLDER" "$STATIC_ASSET_NAME"
          zip -r "${STATIC_ASSET_NAME}.zip" "$STATIC_ASSET_NAME"

      - name: Upload release asset triggered by release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.STATIC_ASSET_NAME }}.zip
          asset_name: ${{ env.STATIC_ASSET_NAME }}.zip
          asset_content_type: application/zip

      - name: Upload release asset using GitHub CLI
        if: github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin 'refs/tags/*:refs/tags/*'
          TAG_NAME=$(git describe --tags --abbrev=0)
          gh release upload "$TAG_NAME" "${STATIC_ASSET_NAME}.zip" --clobber
